[package]
name = "typedids"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
description = "Type-safe ID newtypes via derive macro"
repository = "https://github.com/WyattAu/typed-id"
readme = "README.md"
keywords = ["typedids", "newtype", "uuid", "derive"]
categories = ["rust-patterns"]

[dependencies]
typed-id-derive = { version = "0.1", package = "typed-id-derive", path = "../typed-id-derive" }
uuid = { version = "1", default-features = false }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1"
proptest = "1"

[features]
default = ["std", "uuid_v4", "uuid_v7", "uuid_serde"]
std = ["uuid/std"]
uuid_v4 = ["uuid/v4"]
uuid_v7 = ["uuid/v7", "uuid/std"]
uuid_serde = ["uuid/serde"]
serde_impl = ["dep:serde"]
